modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Lykrast/SheikahFont/issues"
license="All Rights Reserved https://github.com/Lykrast/SheikahFont/blob/main/LICENSE"

[[mods]]
modId="sheikahfont"
version="${file.jarVersion}"
displayName="Sheikah Font"
displayURL="https://modrinth.com/mod/sheikah-font"
logoFile="logo.png"
credits="Darkhax for inspiration, zeldawiki.wiki for info on the cipher and high quality images"
authors="Lykrast"
description='''
Adds the Sheikah alphabet from The Legend of Zelda: Breath of the Wild as a font and banner patterns.
'''

[[dependencies.sheikahfont]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sheikahfont]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"